### ISSUE TITLE
デフォルトアプリが消去できる

### ISSUE THREAD

**Issue by popkechupki** [CoSSeDevelopmentTeam/CPhoneAppMarket#1]
AppMarket1.3.0においてデフォルトのアプリも消去できてしまうバグを見つけました。
消去確認ウインドウのボタンは２つとも「メニューに戻る」の選択肢となっており上を押した場合に上記のバグが発生します。
（消去したアプリはインストールし直す、またはサーバー再起動後にログインすると復活します。）

**Comment by itsu-dev** [comment]
修正します

**Comment by itsu-dev** [comment]
https://github.com/CoSSeDevelopmentTeam/CPhoneAppMarket/commit/5cd4d156bf004d07099e5f02b78d9d208dec2bf2
