### ISSUE TITLE
購入済みを開くと現在インストールしているアプリのみが表示される

### ISSUE THREAD

**Issue by popkechupki** [CoSSeDevelopmentTeam/CPhoneAppMarket#2]
AppMarketv1.3.0で購入済みを開くと現在インストールされているアプリのみが表示され、既に購入済みではあるがその時点でインストールされていないアプリはリストに表示されません。
検索からは過去に購入済み（デフォルト）アプリも探してインストールすることができます。

**Comment by itsu-dev** [comment]
日本語表示がまずかったです、ただしくは「インストール済み」でした。直しておきます。

**Comment by itsu-dev** [comment]
https://github.com/CoSSeDevelopmentTeam/CPhoneAppMarket/commit/5cd4d156bf004d07099e5f02b78d9d208dec2bf2
