### ISSUE TITLE
インストール済み画面のアプリ名が多言語化されていない

### ISSUE THREAD

**Issue by popkechupki** [CoSSeDevelopmentTeam/CPhoneAppMarket#3]
タイトル通りです。日本語設定でアプリ名が英語のものが表示されています。

**Comment by itsu-dev** [comment]
https://github.com/CoSSeDevelopmentTeam/CPhoneAppMarket/commit/ed7f7e0fbfa16869d85fe4cae489c3d4cfbf27a1
